apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgr-product-deployment
  labels:
    app: mgr-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mgr-product
  template:
    metadata:
      labels:
        app: mgr-product
    spec:
      containers:
      - name: mgr-product
        image: asdawas/mgr_product_service:latest
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: mgr-product-secret

---

apiVersion: v1
kind: Service
metadata:
  name: mgr-product-service
  labels:
    app: mgr-product-service
spec:
  type: NodePort
  ports:
  - port: 5432
    protocol: TCP
    name: mgr-product
  selector:
    app: mgr-product