apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgr-stats-deployment
  labels:
    app: mgr-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mgr-stats
  template:
    metadata:
      labels:
        app: mgr-stats
    spec:
      containers:
      - name: mgr-stats
        image: asdawas/mgr_stats_service:latest
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: mgr-stats-secret

---

apiVersion: v1
kind: Service
metadata:
  name: mgr-stats-service
  labels:
    app: mgr-stats-service
spec:
  type: NodePort
  ports:
  - port: 30001
    targetPort: 3000
    nodePort: 30001
    protocol: TCP
    name: mgr-stats-service
  selector:
    app: mgr-stats
