apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgr-product-db-deployment
  labels:
    app: mgr-product-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mgr-product-db
  template:
    metadata:
      labels:
        app: mgr-product-db
    spec:
      containers:
      - name: mgr-product-db
        image: postgres:11
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: mgr-db-secret

---

apiVersion: v1
kind: Service
metadata:
  name: mgr-product-db-service
  labels:
    app: mgr-product-db-service
spec:
  type: NodePort
  ports:
  - port: 5432
    protocol: TCP
    name: mgr-product-db-service
  selector:
    app: mgr-product-db