apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgr-order-db-deployment
  labels:
    app: mgr-order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mgr-order-db
  template:
    metadata:
      labels:
        app: mgr-order-db
    spec:
      containers:
      - name: mgr-order-db
        image: postgres:11
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: mgr-db-secret

---

apiVersion: v1
kind: Service
metadata:
  name: mgr-order-db-service
  labels:
    app: mgr-order-db-service
spec:
  type: NodePort
  ports:
  - port: 30003
    targetPort: 5432
    nodePort: 30003
    protocol: TCP
    name: mgr-order-db-service
  selector:
    app: mgr-order-db
