- hosts: master
  tasks:
  - name: Write worker instance host key to known hosts
    connection: local
    shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"
  - name: Generate join command
    shell: "kubeadm token create --print-join-command"
    register: join_command
  - name: Add join command do join_host
    add_host:
      name: join_host
      join_command: "{{ join_command.stdout_lines[0] }}"

- hosts: workers
  tasks:    
  - name: Join to the cluster
    shell: "{{ hostvars['join_host']['join_command'] }}"
